const STAGES=[{name:'Спора в мху',req:0},{name:'Первые гифы',req:450},{name:'Нить под корнями',req:4500},{name:'Шляпки у камня',req:22000},{name:'Сырой грот',req:90000},{name:'Споровая поляна',req:420000},{name:'Собор гиф',req:1900000},{name:'Ночной лес',req:9500000},{name:'Корень мира',req:42000000},{name:'Единая сеть',req:210000000}];
const UPGRADES=[{id:'pulse',name:'Пульс шляпки',desc:'+1 к импульсу',base:12,grow:1.15,max:80,click:1},{id:'dew',name:'Капля росы',desc:'+0,4 споры/сек',base:42,grow:1.18,max:80,per:0.4},{id:'hypha',name:'Гифа',desc:'+2,6 споры/сек',base:230,grow:1.22,max:40,per:2.6},{id:'cap',name:'Плодовое тело',desc:'+13 спор/сек',base:1700,grow:1.25,max:30,per:13},{id:'web',name:'Сплетение',desc:'×1,45 ко всему',base:42000,grow:2.4,max:8,mult:1.45},{id:'nerve',name:'Нерв сети',desc:'+20 к импульсу',base:72000,grow:1.34,max:40,click:20},{id:'grove',name:'Поляна',desc:'+380 спор/сек',base:390000,grow:1.38,max:16,per:380},{id:'mind',name:'Лесной ум',desc:'+980 спор/сек',base:1600000,grow:1.45,max:12,per:980}];
const CONTRACTS=[{title:'Первый всход',type:'energy',target:200,reward:70,marks:1},{title:'Сорок пульсов',type:'clicks',target:40,reward:280,marks:1},{title:'Три отростка',type:'levels',target:3,reward:170,marks:1},{title:'Шляпки у камня',type:'stage',target:4,reward:1500,marks:2},{title:'Густая сеть',type:'levels',target:14,reward:4500,marks:3}];
const RESEARCH=[{id:'thrum',name:'Глухой стук',desc:'Импульс +25%',cost:3},{id:'reach',name:'Длинная гифа',desc:'Разведка на 25% быстрее',cost:4},{id:'humus',name:'Жирный гумус',desc:'Пассив +15%',cost:5}];
const ROUTES=[{id:'root',name:'К старым корням',min:2,time:60000,minR:220,marks:1},{id:'cave',name:'В сырой грот',min:4,time:120000,minR:1300,marks:2},{id:'deep',name:'К корню мира',min:7,time:180000,minR:7500,marks:3}];
const KEY='myceliumColonySave',ERA_COST=1e6,$=id=>document.getElementById(id);
const fmt=n=>{n=Math.max(0,+n||0);if(n<1000)return(Math.round(n*10)/10).toString().replace('.',',');if(n<1e6)return(n/1e3).toFixed(1).replace('.',',')+' тыс.';if(n<1e9)return(n/1e6).toFixed(2).replace('.',',')+' млн';return(n/1e9).toFixed(2).replace('.',',')+' млрд'};
const fresh=()=>({energy:0,total:0,click:1,per:0,mult:1,prestige:1,up:Object.fromEntries(UPGRADES.map(u=>[u.id,0])),last:Date.now(),sound:true,tutorial:false,grantAt:0,boostUntil:0,boostReady:0,lastFull:0,session:Date.now(),clicks:0,contract:0,baseline:0,marks:0,research:[],probe:null,event:null,nextEvent:Date.now()+8e4,offline:0});
let S=fresh(),last=Date.now(),uiAt=0,visible=true,adPause=false,gpTimer=null,pendingFull=false,audio=null;
const hasRes=id=>S.research.includes(id);
const clickPow=()=>S.click*(hasRes('thrum')?1.25:1)*(S.event?.mode==='click'?2:1);
const perSec=()=>S.per*(hasRes('humus')?1.15:1)*(S.event?.mode==='passive'?2:1)*(S.boostUntil>Date.now()?2:1);
const stage=()=>[...STAGES].reverse().find(x=>S.total>=x.req)||STAGES[0];
const stageI=()=>STAGES.indexOf(stage())+1;
const nextSt=()=>STAGES[STAGES.indexOf(stage())+1]||null;
const cost=u=>Math.floor(u.base*Math.pow(u.grow,S.up[u.id]||0));
function recalc(){let c=1,p=0,m=1;UPGRADES.forEach(u=>{const l=S.up[u.id]||0;if(!l)return;if(u.click)c+=u.click*l;if(u.per)p+=u.per*l;if(u.mult)m*=Math.pow(u.mult,l)});S.click=c*S.prestige*m;S.per=p*S.prestige*m;S.mult=m}
const note=t=>{const n=$('notice');n.textContent=t;n.classList.add('on');clearTimeout(note.t);note.t=setTimeout(()=>n.classList.remove('on'),2200)};
const profile=mode=>{$('profileName').textContent=mode==='cloud'||mode==='sync'?'Облачный слой':'Локальный слой';$('syncStatus').textContent=mode==='sync'?'синхронизация…':mode==='cloud'?'синхронизировано':'на устройстве'};
function play(kind){if(!S.sound)return;audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime,map={hit:[140,70],crit:[280,480],buy:[220,360],warn:[80,50]},[a,b]=map[kind]||map.hit;o.type=kind==='crit'?'triangle':'sine';o.frequency.setValueAtTime(a,now);o.frequency.exponentialRampToValueAtTime(Math.max(40,b),now+.16);g.gain.setValueAtTime(.05,now);g.gain.exponentialRampToValueAtTime(.001,now+.18);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+.2)}
const snapshot=()=>JSON.stringify({...S,event:null});
function save(remote=true){S.last=Date.now();localStorage.setItem(KEY,snapshot());if(!remote||!window.gp?.player?.set)return;clearTimeout(gpTimer);gpTimer=setTimeout(async()=>{try{profile('sync');window.gp.player.set('save',snapshot());await window.gp.player.sync?.();profile('cloud')}catch{profile('local')}},2500)}
function pause(){if(adPause)return;adPause=true;visible=false}function resume(){adPause=false;visible=true;last=Date.now()}
async function rewarded(fn){const gp=window.gp;if(!gp?.ads?.isRewardedAvailable){fn();return true}try{pause();const ok=await gp.ads.showRewardedVideo({showFailedOverlay:true});if(ok){fn();return true}note('Награда не получена');return false}catch{note('Реклама недоступна');return false}finally{resume()}}
async function maybeFull(){const gp=window.gp,now=Date.now();if(!gp?.ads?.isFullscreenAvailable||now-S.lastFull<18e4||now-S.session<6e4)return;try{pause();if(await gp.ads.showFullscreen({showCountdownOverlay:true}))S.lastFull=Date.now()}finally{resume();save(false)}}
window.onGPInit=async gp=>{try{window.gp=gp;await gp.player?.ready;const raw=gp.player.get?.('save');if(raw){const cloud={...fresh(),...JSON.parse(raw)};if((cloud.last||0)>(S.last||0))S=cloud}if(gp.ads?.isPreloaderAvailable)await gp.ads.showPreloader();if(gp.ads?.isStickyAvailable)gp.ads.showSticky();gp.gameStart?.();recalc();render();profile('cloud')}catch{profile('local')}};
function contractVal(c){if(c.type==='energy')return Math.max(0,S.total-S.baseline);if(c.type==='clicks')return Math.max(0,S.clicks-S.baseline);if(c.type==='levels')return Object.values(S.up).reduce((a,b)=>a+b,0)-S.baseline;return stageI()}
function setBase(){const c=CONTRACTS[S.contract];S.baseline=!c?0:c.type==='energy'?S.total:c.type==='clicks'?S.clicks:c.type==='levels'?Object.values(S.up).reduce((a,b)=>a+b,0):0}
function renderShop(){$('shop').innerHTML=UPGRADES.map(u=>{const lvl=S.up[u.id]||0,cst=cost(u),max=lvl>=u.max,can=!max&&S.energy>=cst;return `<button class="item ${can?'ok':'no'}" data-up="${u.id}" ${max?'disabled':''}><span class="mark">${u.name[0]}</span><span><b>${u.name}</b><div style="color:var(--muted);font-size:12px">${u.desc} · ур. ${lvl}</div></span><span class="need">${max?'готово':can?fmt(cst):'ещё '+fmt(cst-S.energy)}</span></button>`}).join('')}
function renderLab(){$('research').innerHTML=RESEARCH.map(r=>{const done=hasRes(r.id);return `<button class="item ${done?'ok':''}" data-res="${r.id}" ${done?'disabled':''}><span class="mark">※</span><span><b>${r.name}</b><div style="color:var(--muted);font-size:12px">${r.desc}</div></span><span class="need">${done?'готово':r.cost+' печатей'}</span></button>`}).join('')}
function renderRoutes(){const act=S.probe,i=stageI();$('routes').innerHTML=ROUTES.map(r=>{const lock=i<r.min,sel=act?.id===r.id;return `<button class="item ${sel?'ok':''}" data-route="${r.id}" ${act||lock?'disabled':''}><span class="mark">∿</span><span><b>${r.name}</b></span><span class="need">${sel?'в пути':lock?'слой '+r.min:'+'+r.marks+' печать'}</span></button>`}).join('')}
function render(){const st=stage(),nx=nextSt(),i=stageI();$('energy').textContent=fmt(S.energy);$('perSec').textContent=fmt(perSec());$('stageName').textContent=st.name;$('stageNum').textContent='СЛОЙ '+String(i).padStart(2,'0');$('grove').dataset.stage=String(i);const pct=nx?Math.min(100,Math.floor((S.total-st.req)/(nx.req-st.req)*100)):100;$('goalPct').textContent=nx?pct+'%':'ГОТОВО';$('goalTitle').textContent=nx?nx.name:'Единая сеть';$('goalDesc').textContent=nx?'осталось '+fmt(nx.req-S.total)+' спор':'Колония заполнила этот слой';$('prestige').textContent='×'+S.prestige.toFixed(2).replace('.',',');const left=Math.max(0,ERA_COST-S.total);$('eraNeed').textContent=left?'Нужно ещё '+fmt(left)+' спор':'Новый слой доступен';$('prestigeBtn').disabled=!!left;const c=CONTRACTS[S.contract];if(!c){$('contractTitle').textContent='Заказы выполнены';$('contractBtn').disabled=true}else{const v=Math.min(c.target,contractVal(c));$('contractTitle').textContent=c.title;$('contractReward').textContent='+'+fmt(c.reward);$('contractProgress').textContent=fmt(v)+' / '+fmt(c.target);$('contractBtn').disabled=v<c.target;$('contractBtn').textContent=v<c.target?'В работе':'Забрать'}const ev=S.event&&S.event.ends>Date.now()?S.event:null;$('eventCard').hidden=!ev;if(ev){$('eventTitle').textContent=ev.title;$('eventDesc').textContent=ev.desc;$('eventTimer').textContent=Math.max(0,Math.ceil((ev.ends-Date.now())/1000))+'c'}const probe=S.probe;if(!probe){$('probeTitle').textContent='Нить разведки';$('probeTimer').textContent='ДОСТУПНО';$('probeRush').hidden=true;$('probeClaim').hidden=true}else{const ready=probe.ends<=Date.now(),route=ROUTES.find(r=>r.id===probe.id);$('probeTitle').textContent=route.name;$('probeTimer').textContent=ready?'НАХОДКА':Math.ceil((probe.ends-Date.now())/1000)+'с';$('probeDesc').textContent=ready?('+'+fmt(probe.reward)+' спор и '+probe.marks+' печатей'):'Гифа ещё в пути';$('probeClaim').hidden=!ready;$('probeRush').hidden=ready||probe.rush}const boostOn=S.boostUntil>Date.now();$('boostBtn').disabled=boostOn||Date.now()<S.boostReady;$('boostBtn').textContent=boostOn?'×2 активно':'×2 рост за рекламу';$('hint').hidden=S.clicks>=6||S.tutorial;renderShop();renderLab();renderRoutes()}
function buy(id){const u=UPGRADES.find(x=>x.id===id);if(!u||S.up[id]>=u.max)return;if(S.energy<cost(u)){play('warn');note('Не хватает спор');return}const before=stage().name;S.energy-=cost(u);S.up[id]++;S.tutorial=true;recalc();play('buy');checkStage(before);render();save()}
function checkStage(prev){if(stage().name===prev)return;$('stageModalTitle').textContent='Открыт «'+stage().name+'»';$('stageModalText').textContent='Колония стала гуще. Новые нити уже видны в слое.';pendingFull=true;$('stageModal').classList.add('on')}
function strike(e){const crit=Math.random()<.08,amt=clickPow()*(crit?5:1),before=stage().name;S.energy+=amt;S.total+=amt;S.clicks++;play(crit?'crit':'hit');const btn=$('hit');btn.classList.add('hit');setTimeout(()=>btn.classList.remove('hit'),160);const f=document.createElement('span');f.className='float';f.textContent=(crit?'ВСПЛЕСК ':'+')+fmt(amt);const r=btn.getBoundingClientRect();f.style.left=((e.clientX||r.left+r.width/2)-r.left)+'px';f.style.top=((e.clientY||r.top+r.height/2)-r.top)+'px';btn.appendChild(f);setTimeout(()=>f.remove(),700);checkStage(before);render();save(false)}
function load(){try{const raw=localStorage.getItem(KEY);if(raw)S={...fresh(),...JSON.parse(raw)};recalc();const elapsed=Math.min(Date.now()-(S.last||Date.now()),8*3600*1000);if(elapsed>15000&&S.per>0){S.offline=elapsed/1000*S.per*.5;$('offlineText').textContent='Колония накопила '+fmt(S.offline)+' спор.';$('offlineModal').classList.add('on')}}catch{S=fresh()}if(!S.baseline&&CONTRACTS[S.contract])setBase()}
function loop(){const now=Date.now(),dt=Math.min((now-last)/1000,.1);last=now;if(!visible||adPause){requestAnimationFrame(loop);return}if(!S.event&&now>S.nextEvent){S.event=Math.random()<.5?{title:'Ночная роса',desc:'Пассив ×2',mode:'passive',ends:now+3e4}:{title:'Споровый ветер',desc:'Импульс ×2',mode:'click',ends:now+3e4};S.nextEvent=now+9e4}if(S.event&&S.event.ends<now)S.event=null;if(perSec()>0){S.energy+=perSec()*dt;S.total+=perSec()*dt}if(now-uiAt>180){render();uiAt=now}requestAnimationFrame(loop)}
$('hit').addEventListener('click',strike);
$('shop').addEventListener('click',e=>{const b=e.target.closest('[data-up]');if(b)buy(b.dataset.up)});
$('research').addEventListener('click',e=>{const b=e.target.closest('[data-res]');if(!b)return;const r=RESEARCH.find(x=>x.id===b.dataset.res);if(!r||hasRes(r.id)||S.marks<r.cost){note('Нужно больше печатей');return}S.marks-=r.cost;S.research.push(r.id);recalc();render();save()});
$('routes').addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(!b||S.probe)return;const r=ROUTES.find(x=>x.id===b.dataset.route);if(stageI()<r.min)return;const t=Math.round(r.time*(hasRes('reach')?.75:1));S.probe={id:r.id,ends:Date.now()+t,reward:Math.max(r.minR,Math.floor(perSec()*18+clickPow()*14)),marks:r.marks,rush:false};render();save()});
$('probeRush').addEventListener('click',()=>{if(!S.probe||S.probe.rush)return;rewarded(()=>{S.probe.ends=Date.now();S.probe.rush=true;render();save()})});
$('probeClaim').addEventListener('click',()=>{const c=S.probe;if(!c||c.ends>Date.now())return;S.energy+=c.reward;S.total+=c.reward;S.marks+=c.marks;S.probe=null;render();save();maybeFull()});
$('contractBtn').addEventListener('click',()=>{const c=CONTRACTS[S.contract];if(!c||contractVal(c)<c.target)return;S.energy+=c.reward;S.total+=c.reward;S.marks+=c.marks;S.contract++;setBase();render();save()});
$('grantBtn').addEventListener('click',()=>{if(Date.now()<S.grantAt){note('Следующая роса позже');return}rewarded(()=>{const add=Math.max(40,Math.floor(perSec()*25+clickPow()*16));S.energy+=add;S.total+=add;S.grantAt=Date.now()+12e4;note('+'+fmt(add)+' спор с поверхности');render();save()})});
$('boostBtn').addEventListener('click',()=>{if(Date.now()<S.boostReady)return;rewarded(()=>{S.boostUntil=Date.now()+12e4;S.boostReady=Date.now()+24e4;render();save()})});
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x===t));['shop','lab','era'].forEach(id=>$(id).hidden=t.dataset.tab!==id)}));
$('soundBtn').addEventListener('click',()=>{S.sound=!S.sound;note(S.sound?'Звук включён':'Звук выключен');save(false)});
$('prestigeBtn').addEventListener('click',()=>{if(S.total>=ERA_COST){$('newPrestige').textContent='×'+(S.prestige+.5).toFixed(2).replace('.',',');$('eraModal').classList.add('on')}});
$('eraNo').onclick=()=>$('eraModal').classList.remove('on');
$('eraYes').onclick=()=>{S.prestige+=.5;S.energy=0;S.total=0;UPGRADES.forEach(u=>S.up[u.id]=0);S.contract=0;S.probe=null;S.tutorial=false;recalc();setBase();$('eraModal').classList.remove('on');render();save()};
$('offlineOk').onclick=()=>{S.energy+=S.offline;S.total+=S.offline;S.offline=0;$('offlineModal').classList.remove('on');render();save()};
$('offlineDouble').onclick=()=>rewarded(()=>{S.energy+=S.offline*2;S.total+=S.offline*2;S.offline=0;$('offlineModal').classList.remove('on');render();save()});
$('stageOk').onclick=()=>{$('stageModal').classList.remove('on');if(pendingFull){pendingFull=false;maybeFull()}};
$('resetBtn').onclick=()=>{if(!confirm('Сжечь колонию и стереть прогресс на этом устройстве?'))return;localStorage.removeItem(KEY);if(window.gp?.player?.set){window.gp.player.set('save','');window.gp.player.sync?.()}S=fresh();recalc();render()};
document.addEventListener('visibilitychange',()=>document.hidden?pause():resume());
window.addEventListener('pagehide',()=>save(false));
load();recalc();render();loop();setInterval(()=>save(),15000);
